kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heketivolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gfs-mirror
---
kind: Pod
apiVersion: v1
metadata:
  name: faketpod
  labels:
    name: fakepod
spec:
  containers:
    - name: bb
      image: busybox
      volumeMounts:
      - mountPath: "/volume"
        name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
       claimName: heketivolumeclaim
