apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heketi-can-change-secrets
subjects:
- kind: ServiceAccount
  name: heketi-service-account
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Defines how to deploy Heketi
  labels:
    glusterfs: heketi-deployment
  name: heketi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        glusterfs: heketi-pod
        name: heketi
      name: heketi
    spec:
      containers:
      - env:
        - name: HEKETI_EXECUTOR
          value: ssh
        - name: HEKETI_SSH_KEYFILE
          value: /key/id_rsa
        - name: HEKETI_SSH_USER
          value: root
        - name: HEKETI_BACKUP_DB_TO_KUBE_SECRET
          value: "true"
        image: heketi/heketi:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 3
        name: heketi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /backupdb
          name: heketi-db-secret
        - mountPath: /key
          name: id-rsa
        - mountPath: /var/lib/heketi
          name: db
      serviceAccount: heketi-service-account
      volumes:
      - name: db
      - name: heketi-db-secret
        secret:
          secretName: heketi-db-backup
      - name: id-rsa
        secret:
          secretName: heketi-id-rsa
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes Heketi Service
  labels:
    deploy-heketi: support
    glusterfs: heketi-service
  name: heketi
spec:
  ports:
  - name: heketi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: heketi

